# Generated by Django 2.1.1 on 2018-12-05 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CB', 'Camibuso'), ('CH', 'Chaqueta'), ('CHC', 'Chaqueta con capota'), ('C', 'Camiseta'), ('BC', 'Buso con capota')], default='CH', max_length=2)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L')], default='M', max_length=2)),
                ('cantidad', models.IntegerField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Colore')),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Prenda')),
            ],
        ),
        migrations.AddField(
            model_name='colore',
            name='prenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Prenda'),
        ),
    ]
