# Generated by Django 2.1.1 on 2018-12-06 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estampado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('CS', 'Cine y series'), ('A', 'Arte'), ('M', 'Musica')], default='CS', max_length=2)),
                ('cantidad', models.IntegerField()),
                ('stock', models.BooleanField()),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Prenda')),
            ],
        ),
    ]
