# Generated by Django 2.1.4 on 2018-12-10 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registro', '0001_initial'),
        ('inventario', '0002_estampado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personalizada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('fabricada', models.BooleanField()),
                ('entregada', models.BooleanField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Colore')),
                ('estampado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Estampado')),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Prenda')),
                ('talla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Talla')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Usuario')),
            ],
        ),
    ]
